import {
  Document as DocxDocument,
  Paragraph,
  TextRun,
  HeadingLevel,
  Packer,
  UnderlineType,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";
import { diffWordsWithSpace, Change } from "diff";
import mammoth from "mammoth";
import { DocumentModel } from "@/models/Document";
import { connectToDatabase } from "@/lib/mongodb";

export interface RedlineSummary {
  originalName: string;
  updatedName: string;
  generatedAt: string;
  additionsCount: number;
  deletionsCount: number;
  modifiedSectionsCount: number;
  unchangedSectionsCount: number;
  totalChanges: number;
  keySubstantiveChanges: string[];
}

export interface RedlineResult {
  docxBuffer: Buffer;
  filename: string;
  summary: RedlineSummary;
}

/**
 * Sanitizes filenames to prevent path traversal or invalid characters.
 */
export function sanitizeFilename(filename: string): string {
  return filename.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/\.+/g, ".");
}

/**
 * Normalizes text to test for whitespace-only/formatting variations.
 */
function normalizeText(text: string): string {
  return text.toLowerCase().replace(/[\r\n\t]+/g, " ").replace(/\s+/g, " ").trim();
}

/**
 * Extracts paragraphs from a DOCX buffer using Mammoth.
 */
async function extractParagraphs(buffer: Buffer): Promise<string[]> {
  const result = await mammoth.extractRawText({ buffer });
  const rawText = (result.value || "").replace(/\r\n/g, "\n").trim();
  if (rawText.length === 0) {
    throw new Error("The DOCX document contains no readable text or is empty.");
  }
  return rawText
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

export const redlineService = {
  /**
   * Generates a tracked-change redline DOCX by comparing an original and updated DOCX document.
   * Produces a valid .docx file with additions (green underline) and deletions (red strikethrough).
   */
  async generateRedline(
    originalBuffer: Buffer,
    updatedBuffer: Buffer,
    originalFilename = "Original_Contract.docx",
    updatedFilename = "Updated_Contract.docx"
  ): Promise<RedlineResult> {
    const cleanOrigName = sanitizeFilename(originalFilename);
    const cleanUpdName = sanitizeFilename(updatedFilename);

    // 1. Extract paragraphs from both DOCX documents
    const origParagraphs = await extractParagraphs(originalBuffer);
    const updParagraphs = await extractParagraphs(updatedBuffer);

    // 2. Perform paragraph alignment and word-level diffing
    let additionsCount = 0;
    let deletionsCount = 0;
    let modifiedSectionsCount = 0;
    let unchangedSectionsCount = 0;
    const keySubstantiveChanges: string[] = [];

    const docxParagraphs: Paragraph[] = [];

    // Document Header & Metadata Banner in DOCX
    docxParagraphs.push(
      new Paragraph({
        text: "REDLINED CONTRACT COMPARISON",
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Generated By: ", bold: true }),
          new TextRun({ text: "FileMentor AI Document Intelligence Engine" }),
        ],
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Base Contract: ", bold: true }),
          new TextRun({ text: cleanOrigName }),
          new TextRun({ text: "  |  Updated Contract: ", bold: true }),
          new TextRun({ text: cleanUpdName }),
        ],
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Comparison Date: ", bold: true }),
          new TextRun({ text: new Date().toLocaleString() }),
        ],
        spacing: { after: 200 },
      }),
      new Paragraph({
        text: "REVISION MARKUP LEGEND:",
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 150, after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: "• Inserted / Added Text",
            color: "008800",
            underline: { type: UnderlineType.SINGLE },
            bold: true,
          }),
          new TextRun({ text: "    " }),
          new TextRun({
            text: "• Deleted / Removed Text",
            color: "CC0000",
            strike: true,
          }),
          new TextRun({ text: "    • Unchanged Text" }),
        ],
        spacing: { after: 350 },
      })
    );

    // 3. Compare corresponding paragraphs
    const maxLen = Math.max(origParagraphs.length, updParagraphs.length);

    for (let i = 0; i < maxLen; i++) {
      const origText = origParagraphs[i] || "";
      const updText = updParagraphs[i] || "";

      // Case A: Section added in updated document
      if (!origText && updText) {
        additionsCount++;
        modifiedSectionsCount++;
        keySubstantiveChanges.push(`Added section: "${updText.slice(0, 80)}..."`);

        docxParagraphs.push(
          new Paragraph({
            children: [
              new TextRun({
                text: updText,
                color: "008800",
                underline: { type: UnderlineType.SINGLE },
                bold: true,
              }),
            ],
            spacing: { after: 200 },
          })
        );
        continue;
      }

      // Case B: Section removed in updated document
      if (origText && !updText) {
        deletionsCount++;
        modifiedSectionsCount++;
        keySubstantiveChanges.push(`Removed section: "${origText.slice(0, 80)}..."`);

        docxParagraphs.push(
          new Paragraph({
            children: [
              new TextRun({
                text: origText,
                color: "CC0000",
                strike: true,
              }),
            ],
            spacing: { after: 200 },
          })
        );
        continue;
      }

      // Case C: Both sections exist
      if (normalizeText(origText) === normalizeText(updText)) {
        // Identical wording (formatting-only variation)
        unchangedSectionsCount++;
        const isHeading =
          origText.toUpperCase() === origText && origText.length < 100;

        docxParagraphs.push(
          new Paragraph({
            text: updText,
            heading: isHeading ? HeadingLevel.HEADING_2 : undefined,
            spacing: { after: 200 },
          })
        );
      } else {
        // Substantive textual modification: Word-level diff
        modifiedSectionsCount++;
        const diffChanges: Change[] = diffWordsWithSpace(origText, updText);
        const runs: TextRun[] = [];

        let hadAdd = false;
        let hadDel = false;

        for (const change of diffChanges) {
          if (change.added) {
            hadAdd = true;
            additionsCount++;
            runs.push(
              new TextRun({
                text: change.value,
                color: "008800",
                underline: { type: UnderlineType.SINGLE },
                bold: true,
              })
            );
          } else if (change.removed) {
            hadDel = true;
            deletionsCount++;
            runs.push(
              new TextRun({
                text: change.value,
                color: "CC0000",
                strike: true,
              })
            );
          } else {
            runs.push(
              new TextRun({
                text: change.value,
                color: "222222",
              })
            );
          }
        }

        if (hadAdd || hadDel) {
          const sampleChange = diffChanges
            .filter((c) => c.added || c.removed)
            .map((c) => (c.added ? `[+] "${c.value.trim()}"` : `[-] "${c.value.trim()}"`))
            .slice(0, 2)
            .join(" ");
          keySubstantiveChanges.push(`Modified paragraph ${i + 1}: ${sampleChange}`);
        }

        docxParagraphs.push(
          new Paragraph({
            children: runs,
            spacing: { after: 200 },
          })
        );
      }
    }

    // 4. Construct valid DOCX Document
    const doc = new DocxDocument({
      sections: [
        {
          properties: {},
          children: docxParagraphs,
        },
      ],
    });

    const docxBuffer = await Packer.toBuffer(doc);
    const outputFilename = `Redline_${cleanOrigName.replace(/\.docx$/i, "")}_vs_${cleanUpdName.replace(/\.docx$/i, "")}.docx`;

    const summary: RedlineSummary = {
      originalName: cleanOrigName,
      updatedName: cleanUpdName,
      generatedAt: new Date().toISOString(),
      additionsCount,
      deletionsCount,
      modifiedSectionsCount,
      unchangedSectionsCount,
      totalChanges: additionsCount + deletionsCount,
      keySubstantiveChanges: keySubstantiveChanges.slice(0, 10),
    };

    return {
      docxBuffer,
      filename: outputFilename,
      summary,
    };
  },

  /**
   * Helper to load DOCX buffer for a document stored in MongoDB.
   */
  async getDocumentBuffer(documentId: string): Promise<{ buffer: Buffer; filename: string }> {
    const cleanId = (documentId || "").trim();
    if (!cleanId || cleanId.length > 100 || !/^[a-zA-Z0-9_-]+$/.test(cleanId)) {
      throw new Error(`Invalid document ID format: "${documentId}".`);
    }

    await connectToDatabase();
    const doc = await DocumentModel.findById(cleanId).lean();
    if (!doc) {
      throw new Error(`Document with ID "${documentId}" was not found.`);
    }

    const isDocx =
      doc.fileType === "docx" ||
      doc.mimeType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
      doc.originalFilename.toLowerCase().endsWith(".docx");

    if (!isDocx) {
      throw new Error(
        `Document "${doc.originalFilename}" is not a DOCX document. Redlining only supports DOCX files.`
      );
    }

    // If storagePath exists, read from storagePath
    if (doc.storagePath) {
      const fs = await import("fs");
      if (fs.existsSync(doc.storagePath)) {
        const buffer = fs.readFileSync(doc.storagePath);
        return { buffer, filename: doc.originalFilename };
      }
    }

    // If text exists, create a minimal DOCX buffer from extractedText
    const docx = await import("docx");
    const paragraphs = (doc.extractedText || "")
      .split(/\n\s*\n/)
      .map((p: string) => new docx.Paragraph({ text: p.trim(), spacing: { after: 200 } }));

    const tempDoc = new docx.Document({
      sections: [{ children: paragraphs }],
    });
    const buffer = await docx.Packer.toBuffer(tempDoc);
    return { buffer, filename: doc.originalFilename };
  },
};
